---
# Workaround to gather facts in certain scenarios when filtering based on tags.
# https://github.com/ansible/ansible/issues/57529#issuecomment-513143430
- hosts: all

# We need to know the user even when 'become'ing later on.
# Some roles depend on 'ansible_user' for this but that may not
# be present. See https://github.com/ansible/ansible/issues/23530
# So, we set some facts ourselves.
- hosts: all
  tasks:
    - name: Run whoami to determine username
      command: whoami
      register: username
    - set_fact:
        username: "{{ username.stdout }}"
        ansible_user: "{{ ansible_user_id }}"

- hosts: all
  become: true
  tasks:
    - import_tasks: tasks/packages.yml

- hosts: all
  become: true

  vars_files:
    - vars/swap.yml

  roles:
    - { role: geerlingguy.swap }

- hosts: all
  become: true
  name: Install NodeJS, PHP, and composer

  vars_files:
    - vars/nodejs.yml
    - vars/php.yml

  pre_tasks:
    - name: Add repository for packages
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

  roles:
    - { role: geerlingguy.php, tags: ["php"] }
    - { role: geerlingguy.composer, tags: ["composer"] }
    - { role: geerlingguy.nodejs, tags: ["nodejs"] }

- hosts: all
  vars_files:
    - vars/yakht.yml
  tasks:
    - import_tasks: tasks/fishshell.yml
      when: install_shell == "fish"

- hosts: all
  vars_files:
    - vars/lando.yml
  tasks:
    - import_tasks: tasks/lando.yml
