---
# Workaround to gather facts in certain scenarios when filtering based on tags.
# https://github.com/ansible/ansible/issues/57529#issuecomment-513143430
- hosts: all

- hosts: all
  tasks:
    - name: Run whoami to determine username
      command: whoami
      register: username
    - set_fact:
        username: "{{ username.stdout }}"

- hosts: all
  become: true
  tasks:
    - import_tasks: tasks/packages.yml

- hosts: all
  become: true
  name: Install PHP and composer

  vars_files:
    - vars/php.yml

  pre_tasks:
    - name: Add repository for packages
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

  roles:
    - { role: geerlingguy.php, tags: ["php"] }
    - { role: geerlingguy.composer, tags: ["composer"] }

- hosts: all
  tasks:
    - import_tasks: tasks/fishshell.yml
