---
roles:
  - src: geerlingguy.firewall
  - src: geerlingguy.php
  - src: geerlingguy.composer
  - src: geerlingguy.nodejs
  - src: geerlingguy.swap

collections:
  - name: ansible.posix
  - name: community.general
