---
- become: true
  import_tasks: fishshell-Ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Find fish shell path
  command: "which fish"
  register: fish_path

- name: Change default shell
  become: true
  user:
    name: "{{ username }}"
    shell: "{{ fish_path.stdout }}"

- name: Get OMF installer
  ansible.builtin.git:
    repo: https://github.com/oh-my-fish/oh-my-fish
    dest: /tmp/omf

- name: Install OMF
  command: fish /tmp/omf/bin/install --offline --yes --noninteractive

- name: Get starship installer
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-installer.sh
    mode: 0777
  when: install_starship == true

- name: Install starship
  become: true
  command: /tmp/starship-installer.sh --yes
  when: install_starship == true

- name: Add starship to fish-shell
  ansible.builtin.lineinfile:
    dest: ~/.config/fish/config.fish
    state: present
    create: true
    regexp: "^starship"
    line: "starship init fish | source"
  when: install_starship == true

- name: Remove installer files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/omf
    - /tmp/starship-installer.sh
