---
- name: Add package repositories
  import_tasks: packages-Debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install base packages
  package:
    name:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - wget
      - zip
    state: latest

- name: Install Python packages
  package:
    name:
      - python3-pip
      - python3-venv
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker
  import_tasks: docker.yml
